### ISSUE TITLE
Hey its taking too long

### ISSUE THREAD

**Issue by hosseinpourziyaie** [CyanSquid/Arxan-Deob-C#1]
Any rough idea of how much it would take for deobfuscation finish?
its been 1 hour i started tool on bo3 dump and i dont want to terminate it without knowing and loose progress

**Comment by CyanSquid** [comment]
Hey, sorry for the late reply. Make sure you compile in Release mode for the fastest result. 
I haven't tested it on BO3 myself, I'll make a dump later and check it out.

**Comment by hosseinpourziyaie** [comment]
Its ok. i did shut down the process as i supposed it got into some kind of infinite loop or something. will try to add some extended debugging logs to see what causing it. btw why dont you print logs directly to console window rather than writing logs with io?

**Comment by CyanSquid** [comment]
I find it more useful than just printing it to the console. For example, using the deobfuscator on GTA5 produces over 120'000 lines of output. Printing that to the console would take too long.

I know you can redirect the console like:

```
arxandeobc dump.exe > out.log
```

But I just found it easier to make the program do it!

**Comment by hosseinpourziyaie** [comment]
checked with breakpoint(`print(HERE)` to be honest) it sticks in this function ---> deobfuscator::skip_jmps

**Comment by CyanSquid** [comment]
Thank you, I'll get it fixed either tonight or tomorrow.

**Comment by CyanSquid** [comment]
I've pushed an update that might fix the infinite loop. I couldn't test it on BO3 since it turns out I only have BO2.
